- App.tsx
- package-lock.json
- package.json
- src/screens/Category.tsx
- src/screens/HomeScreen.tsx
- src/styles/CategoryStyles.ts
- src/types/navigation.ts
Built this repo based on Luke's refactor of CSS styling and continued building it in that pattern.
Built a starter categories page. It is routed from the home page and will take the ID and name from the home page to start with.
Fixed an issue where the Home button on the nav bar wasn't going back to home once on the Categories page.
> Scottdavis08 c14 16 category component on main page that goes to new page

- App.tsx
- src/screens/Category.tsx
- src/screens/HomeScreen.tsx
- src/types/navigation.ts
- src/utils/slugify.ts
Url will be more concise without breaking function.
> Lucasferrari4 c14 32 configure urls to use path parameters instead of query

- babel.config.js
- package-lock.json
- package.json
Re-add babel
https://linear.app/c14-p3-renewu/issue/C14-79/re-add-babel-into-refactored-fe
> re-add babel

- package-lock.json
- package.json
Also lopped this in with https://linear.app/c14-p3-renewu/issue/C14-72/bug-auth-branch-fe-not-running-after-latest-main-merge as not significant enough change to make own branch
> install missing react-native-picker

- package-lock.json
- src/screens/Items.tsx
- src/styles/ItemStyle.ts
styles were off after running on mobile make changes to look nice for shirts
> Fix styles for mobile

- package-lock.json
- src/components/CustomizationOptionGrid.tsx
- src/components/CustomizationProgress.tsx
- src/screens/ItemDetails.tsx
- src/screens/Items.tsx
- src/styles/CustomizationProgressStyles.ts
- src/styles/CustomizationScreenWrapperStyles.ts
- src/styles/ItemStyle.ts
https://github.com/user-attachments/assets/a86b9150-acb3-4b5b-86ef-837a7d45e89d
> Lucasferrari4 c14 88 bug customization page error

- README.md
- src/screens/HomeScreen.tsx
- src/screens/Items.tsx
- src/screens/LoginScreen.tsx
- src/screens/RegisterScreen.tsx
- src/styles/HomeScreenStyles.ts
- src/types/customerData.ts
- src/utils/dropdownUtils.ts
Feeds off PR #35, so should be much smaller once that is merged into main.
- Fixes the login button to navigate to the login page.
- Adds a temporary button to the home screen to open the Body Scan page for testing.
- Fixes registration so it will call the API and create a customer while passing the firebaseUID (requires the backend PR as well).
- Set up the back button with proper pathing logic to get back to the previous page from login and registration without going in a circle.
- Created a helper function so when using drop down menu's (like the logout button), made sure it would close if the user clicked outside of the menu. Applied this to the 4 menu buttons currently implemented.
> Scottdavis08 c14 100 configure login process

- App.tsx
- src/screens/Cart.jsx
- src/screens/customization/CustomizationScreen.tsx
- src/styles/CartScreenStyles.ts
- src/types/navigation.ts
Added a default cart screen. Logic will navigate to it after all Customizations have been chosen.
> feat: Added the cart page to be navigated at the end of customization.

- .github/copilot.json
- src/components/address/Address.tsx
- src/components/address/AddressField.tsx
- src/components/address/BillingAddress.tsx
- src/components/address/CountryPickerField.tsx
- src/components/address/SavedAddressDropdown.tsx
- src/components/address/ShippingAddress.tsx
- src/components/address/StatePickerField.tsx
- src/screens/CheckoutScreen.tsx
- src/styles/AddressStyles.ts
- src/styles/SavedAddressDropdownStyles.ts
- src/types/address.types.ts
- src/utils/sizes.ts
Built a dropdown to display saved addresses for easy user (and tester) entry.
Builds off other front end PRs. Also requires back end PR 16 to be running to access Address data.
> Scottdavis08 c14 134 saved address dropdown

- src/components/address/BillingAddress.tsx
- src/components/address/ShippingAddress.tsx
- src/screens/CheckoutScreen.tsx
- src/styles/AddressStyles.ts
- src/types/address.types.ts
- src/utils/addressValidation.ts
Quite weak at the moment, but adds validation via callback. Currently all fields validate the second the page opens, but it's good enough for now.
> Scottdavis08 c14 125 finish placing order

- src/screens/PaymentScreen.tsx
- src/screens/customization/CustomizationScreen.tsx
- src/services/customization.service.ts
- src/styles/PaymentScreenStyles.ts
Fairly quick one to display the item summary from the cart context on the final stripe payment page.
> Scottdavis08 c14 84 order summary

- App.tsx
- package-lock.json
- package.json
- src/screens/Cart.tsx
- src/screens/CheckoutScreen.tsx
- src/screens/Items.tsx
- src/screens/LoginScreen.tsx
- src/screens/PaymentScreen.tsx
- src/types/navigation.ts
Creating largely to satisfy Linear as a ticket was made for this. It's also been merged into the fixing of the cart navigation as that's where it was tested. Ended up being easier to fix than expected, but can technically be skipped if c14-130 has been merged.
> Scottdavis08 c14 133 fix nav on login

- App.tsx
- src/navigation/BottomTabNavigator.tsx
- src/screens/AccountScreen.tsx
- src/styles/AccountScreenStyles.ts
- src/types/navigation.ts
Added an Account screen that allows the user to peruse their information if they're logged in.
For now none of the user account info goes anywhere.
For some strange reason I'm getting a bug where only the login and register buttons don't print the text on the account screen but there's no logical reason for it.
> Scottdavis08 c14 131 build account navigation

- App.tsx
- src/navigation/BottomTabNavigator.tsx
- src/screens/AccountScreen.tsx
- src/screens/BodyScanScreen.tsx
- src/screens/ManualMeasurementInput.tsx
- src/screens/MeasurementScreen.tsx
- src/styles/AccountScreenStyles.ts
- src/styles/BodyScanStyles.ts
- src/styles/MeasurementScreenStyles.ts
- src/types/navigation.ts
Bit bigger than I was expecting. I think a few Navigation issues have been added in gradually over time.
Made the navigation Types more consistent (I hope) while troubleshooting what ended up being an unrelated routing issue.
Made a new Measurement Screen where you can select the type of measurement you want to proceed with.
Added SafeAreaView to all the measurement windows as well as proper navigation header.
> Scottdavis08 c14 129 build measurement navigation

- package-lock.json
- src/context/CustomizationContext.tsx
- src/screens/customization/CustomizationScreen.tsx
> C14 120 fix lock future frontend

- src/screens/CheckoutScreen.tsx
Fixed an issue created from previous merge conflicts where the field validation was broken.
> scottdavis08-c14-153-fix-shipping-address-validation

- src/components/checkout/CheckoutLoginStatus.tsx
- src/screens/AccountScreen.tsx
Small fix to the name that displays on the checkout and account pages to come from the customer account instead of the firebase record.
> Scottdavis08 c14 156 checkout displays email

- src/screens/BodyScanScreen.tsx
- src/screens/CheckoutScreen.tsx
- src/screens/ManualMeasurementInput.tsx
- src/styles/CheckoutScreenStyles.ts
- src/styles/ManualMeasurementInput.ts
Reasonably small. Allows the keyboard to pop the screen up so fields don't get hidden when you're trying to type. 
The manual measurement input page also implemented a next button for navigation, but it's been tedious enough to implement and doesn't work the way I'd like so not replicating it on the rest. right now.
> Scottdavis08 c14 165 fix keyboard functionality

- src/screens/BodyScanScreen.tsx
- src/screens/ManualMeasurementInput.tsx
Require authentication to submit to the body scan.
> Scottdavis08 c14 150 add login to body scan

- src/styles/AccountScreenStyles.ts
Quick one to fix the Login and Create Account buttons. Damn padding was pushing the text out of the button and made the button bigger.
> scottdavis08-c14-172-fix-login-and-registration-buttons

- src/screens/ItemDetails.tsx
- src/screens/customization/CustomizationScreen.tsx
- src/styles/ItemDetailsStyles.ts
Some styling changes to better flesh out the Item Details page. Added a hard coded Fabric Details description to the drop down instead of duping the desc.
> scottdavis08-c14-173-redesign-the-item-details-page
